development: &default
  adapter: postgresql
  encoding: unicode
  database: your-project_development
  pool: 5

  host: localhost
  port: 5432
 
test: &test
  <<: *default
  database: your-project_development

