# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development: &default
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
# username: <%= ENV.fetch('DB_USERNAME', 'your-project') %>
# password: <%= ENV.fetch('DB_PASSWORD', 'your-project') %>
# host: <%= ENV.fe#tch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
# port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
 
test: &test
  <<: *default
  database: db/development.sqlite3


